import type { RoleKey, RoleShellConfig } from "./types";

const PRODUCT_LABEL = "SchoolManage";

export const SHELL_NAV_CONFIG: Record<RoleKey, RoleShellConfig> = {
  admin: {
    role: "admin",
    roleLabel: "Admin",
    productLabel: PRODUCT_LABEL,
    items: [
      { href: "/admin/dashboard", label: "Dashboard", icon: "home" },
      { href: "/admin/students", label: "Students", icon: "users", activePrefix: "/admin/students" },
      {
        href: "/admin/academic",
        label: "Academic",
        icon: "bookOpen",
        activePrefix: "/admin/academic",
        children: [
          { href: "/admin/academic", label: "Overview", icon: "bookOpen", exactMatch: true },
          {
            href: "/admin/academic/setup",
            label: "Setup status",
            icon: "clipboardCheck",
            activePrefix: "/admin/academic/setup",
          },
          {
            href: "/admin/academic/structure",
            label: "Structure setup",
            icon: "school",
            activePrefix: "/admin/academic/structure",
          },
          {
            href: "/admin/academic/years",
            label: "Academic years",
            icon: "calendar",
            activePrefix: "/admin/academic/years",
          },
          { href: "/admin/academic/terms", label: "Terms", icon: "calendar", activePrefix: "/admin/academic/terms" },
          { href: "/admin/academic/classes", label: "Classes", icon: "school", activePrefix: "/admin/academic/classes" },
          {
            href: "/admin/academic/subjects",
            label: "Subjects",
            icon: "bookOpen",
            activePrefix: "/admin/academic/subjects",
          },
          {
            href: "/admin/academic/assignments",
            label: "Teaching assignments",
            icon: "users",
            activePrefix: "/admin/academic/assignments",
          },
          {
            href: "/admin/academic/class-teachers",
            label: "Class teachers",
            icon: "graduationCap",
            activePrefix: "/admin/academic/class-teachers",
          },
          {
            href: "/admin/academic/class-subjects",
            label: "Class subjects",
            icon: "clipboardCheck",
            activePrefix: "/admin/academic/class-subjects",
          },
          {
            href: "/admin/academic/teacher-assignments",
            label: "Subject teachers",
            icon: "users",
            activePrefix: "/admin/academic/teacher-assignments",
          },
          {
            href: "/admin/academic/timetable",
            label: "Timetable",
            icon: "calendar",
            activePrefix: "/admin/academic/timetable",
          },
          {
            href: "/admin/academic/curriculum",
            label: "Curriculum setup",
            icon: "bookOpen",
            activePrefix: "/admin/academic/curriculum",
          },
          {
            href: "/admin/academic/combinations",
            label: "Subject combinations",
            icon: "school",
            activePrefix: "/admin/academic/combinations",
          },
          {
            href: "/admin/academic/cbc-strands",
            label: "CBC strands",
            icon: "clipboardCheck",
            activePrefix: "/admin/academic/cbc-strands",
            sectionLabel: "Competency assessment",
          },
        ],
      },
      {
        href: "/admin/assessment",
        label: "Assessment",
        icon: "clipboardCheck",
        activePrefix: "/admin/assessment",
        children: [
          { href: "/admin/assessment", label: "Overview", icon: "clipboardCheck", exactMatch: true },
          {
            href: "/admin/assessment/guide",
            label: "How assessment works",
            icon: "bookOpen",
            activePrefix: "/admin/assessment/guide",
          },
          {
            href: "/admin/assessment/cbc",
            label: "Competency oversight",
            icon: "clipboardCheck",
            activePrefix: "/admin/assessment/cbc",
            sectionLabel: "Competency assessment",
          },
          {
            href: "/admin/assessment/rules",
            label: "Assessment rules",
            icon: "clipboardCheck",
            activePrefix: "/admin/assessment/rules",
            sectionLabel: "CA & grading",
          },
          {
            href: "/admin/academic/grading-scales",
            label: "Grading scales",
            icon: "barChart3",
            activePrefix: "/admin/academic/grading-scales",
          },
          {
            href: "/admin/exams",
            label: "Formal exams",
            icon: "fileText",
            activePrefix: "/admin/exams",
            sectionLabel: "Formal exams",
          },
          {
            href: "/admin/assessment/alevel",
            label: "A-Level assessment",
            icon: "graduationCap",
            activePrefix: "/admin/assessment/alevel",
            sectionLabel: "A-Level assessment",
          },
        ],
      },
      { href: "/admin/reports", label: "Reports", icon: "fileBarChart2", activePrefix: "/admin/reports" },
      {
        href: "/admin/attendance",
        label: "Attendance",
        icon: "barChart3",
        activePrefix: "/admin/attendance",
      },
      {
        href: "/admin/fees/publish",
        label: "Fees",
        icon: "creditCard",
        activePrefix: "/admin/fees",
        children: [
          {
            href: "/admin/fees/publish",
            label: "Publish & bill",
            icon: "creditCard",
            activePrefix: "/admin/fees/publish",
          },
          {
            href: "/admin/fees/structure",
            label: "Fee structure",
            icon: "receipt",
            activePrefix: "/admin/fees/structure",
          },
          {
            href: "/admin/fees/overview",
            label: "Billing overview",
            icon: "barChart3",
            activePrefix: "/admin/fees/overview",
          },
          {
            href: "/admin/fees/reports",
            label: "Financial reports",
            icon: "fileBarChart2",
            activePrefix: "/admin/fees/reports",
          },
        ],
      },
      { href: "/admin/users", label: "Users", icon: "graduationCap", activePrefix: "/admin/users" },
      { href: "/admin/settings", label: "Settings", icon: "school", activePrefix: "/admin/settings" },
      {
        href: "/admin/audit-logs",
        label: "Audit logs",
        icon: "shield",
        activePrefix: "/admin/audit-logs",
      },
    ],
  },
  headteacher: {
    role: "headteacher",
    roleLabel: "Headteacher",
    productLabel: PRODUCT_LABEL,
    items: [
      { href: "/headteacher/dashboard", label: "Dashboard", icon: "home" },
      {
        href: "/headteacher/students",
        label: "Students",
        icon: "users",
        activePrefix: "/headteacher/students",
      },
      {
        href: "/headteacher/academic",
        label: "Academic",
        icon: "bookOpen",
        activePrefix: "/headteacher/academic",
        children: [
          { href: "/headteacher/academic", label: "Overview", icon: "bookOpen", exactMatch: true },
          {
            href: "/headteacher/academic/assignments",
            label: "Teaching assignments",
            icon: "users",
            activePrefix: "/headteacher/academic/assignments",
          },
          {
            href: "/headteacher/academic/class-teachers",
            label: "Class teachers",
            icon: "graduationCap",
            activePrefix: "/headteacher/academic/class-teachers",
          },
          {
            href: "/headteacher/academic/class-subjects",
            label: "Class subjects",
            icon: "clipboardCheck",
            activePrefix: "/headteacher/academic/class-subjects",
          },
          {
            href: "/headteacher/academic/teacher-assignments",
            label: "Subject teachers",
            icon: "users",
            activePrefix: "/headteacher/academic/teacher-assignments",
          },
          {
            href: "/headteacher/academic/timetable",
            label: "Timetable",
            icon: "calendar",
            activePrefix: "/headteacher/academic/timetable",
          },
        ],
      },
      {
        href: "/headteacher/assessment",
        label: "Assessment",
        icon: "clipboardCheck",
        activePrefix: "/headteacher/assessment",
        children: [
          { href: "/headteacher/assessment", label: "Overview", icon: "clipboardCheck", exactMatch: true },
          {
            href: "/headteacher/assessment/guide",
            label: "How assessment works",
            icon: "bookOpen",
            activePrefix: "/headteacher/assessment/guide",
          },
          {
            href: "/headteacher/assessment/cbc",
            label: "Competency assessment",
            icon: "clipboardCheck",
            activePrefix: "/headteacher/assessment/cbc",
            sectionLabel: "Competency assessment",
          },
          {
            href: "/headteacher/assessment/alevel",
            label: "A-Level",
            icon: "graduationCap",
            activePrefix: "/headteacher/assessment/alevel",
            sectionLabel: "CA & grading",
          },
          {
            href: "/headteacher/exams",
            label: "Formal exams",
            icon: "fileText",
            activePrefix: "/headteacher/exams",
          },
        ],
      },
      {
        href: "/headteacher/reports",
        label: "Report Cards",
        icon: "fileBarChart2",
        activePrefix: "/headteacher/reports",
      },
      {
        href: "/headteacher/analytics",
        label: "Analytics",
        icon: "barChart3",
        activePrefix: "/headteacher/analytics",
      },
      {
        href: "/headteacher/attendance",
        label: "Attendance",
        icon: "calendar",
        activePrefix: "/headteacher/attendance",
      },
      {
        href: "/headteacher/fees",
        label: "Finance",
        icon: "creditCard",
        activePrefix: "/headteacher/fees",
        children: [
          { href: "/headteacher/fees", label: "Overview", icon: "creditCard", exactMatch: true },
          {
            href: "/headteacher/fees/reports",
            label: "Term reports",
            icon: "fileBarChart2",
            activePrefix: "/headteacher/fees/reports",
          },
          {
            href: "/headteacher/fees/payments",
            label: "Payments",
            icon: "receipt",
            activePrefix: "/headteacher/fees/payments",
          },
          {
            href: "/headteacher/fees/invoices",
            label: "Invoices",
            icon: "receipt",
            activePrefix: "/headteacher/fees/invoices",
          },
        ],
      },
      {
        href: "/headteacher/users",
        label: "Users",
        icon: "graduationCap",
        activePrefix: "/headteacher/users",
      },
    ],
  },
  "class-teacher": {
    role: "class-teacher",
    roleLabel: "Class teacher",
    productLabel: PRODUCT_LABEL,
    items: [
      { href: "/class-teacher/dashboard", label: "Dashboard", icon: "home" },
      {
        href: "/class-teacher/students",
        label: "My classes",
        icon: "school",
        activePrefix: "/class-teacher/students",
      },
      {
        href: "/class-teacher/timetable",
        label: "Timetable",
        icon: "bookOpen",
        activePrefix: "/class-teacher/timetable",
      },
      {
        href: "/class-teacher/attendance",
        label: "Attendance",
        icon: "clipboardCheck",
        activePrefix: "/class-teacher/attendance",
      },
      {
        href: "/class-teacher/assessment/cbc",
        label: "Assessment",
        icon: "clipboardCheck",
        activePrefix: "/class-teacher/assessment",
        children: [
          {
            href: "/class-teacher/assessment/guide",
            label: "How assessment works",
            icon: "bookOpen",
            activePrefix: "/class-teacher/assessment/guide",
          },
          {
            href: "/class-teacher/assessment/cbc",
            label: "Competency assessment",
            icon: "clipboardCheck",
            activePrefix: "/class-teacher/assessment/cbc",
            sectionLabel: "Competency assessment",
          },
          {
            href: "/class-teacher/assessment/alevel",
            label: "A-Level assessment",
            icon: "graduationCap",
            activePrefix: "/class-teacher/assessment/alevel",
            sectionLabel: "CA & grading",
          },
        ],
      },
      { href: "/class-teacher/exams", label: "Exams", icon: "fileText", activePrefix: "/class-teacher/exams" },
      {
        href: "/class-teacher/comments",
        label: "Report comments",
        icon: "fileBarChart2",
        activePrefix: "/class-teacher/comments",
      },
    ],
  },
  "subject-teacher": {
    role: "subject-teacher",
    roleLabel: "Subject teacher",
    productLabel: PRODUCT_LABEL,
    items: [
      { href: "/subject-teacher/dashboard", label: "Dashboard", icon: "home" },
      {
        href: "/subject-teacher/students",
        label: "My classes",
        icon: "users",
        activePrefix: "/subject-teacher/students",
      },
      {
        href: "/subject-teacher/timetable",
        label: "Timetable",
        icon: "bookOpen",
        activePrefix: "/subject-teacher/timetable",
      },
      {
        href: "/subject-teacher/attendance",
        label: "Attendance",
        icon: "clipboardCheck",
        activePrefix: "/subject-teacher/attendance",
      },
      {
        href: "/subject-teacher/assessment/cbc",
        label: "Assessment",
        icon: "clipboardCheck",
        activePrefix: "/subject-teacher/assessment",
        children: [
          {
            href: "/subject-teacher/assessment/guide",
            label: "How assessment works",
            icon: "bookOpen",
            activePrefix: "/subject-teacher/assessment/guide",
          },
          {
            href: "/subject-teacher/assessment/cbc",
            label: "Competency assessment",
            icon: "clipboardCheck",
            activePrefix: "/subject-teacher/assessment/cbc",
            sectionLabel: "Competency assessment",
          },
          {
            href: "/subject-teacher/assessment/alevel",
            label: "A-Level assessment",
            icon: "bookOpen",
            activePrefix: "/subject-teacher/assessment/alevel",
            sectionLabel: "CA & grading",
          },
        ],
      },
      { href: "/subject-teacher/exams", label: "Exams", icon: "fileText", activePrefix: "/subject-teacher/exams" },
    ],
  },
  bursar: {
    role: "bursar",
    roleLabel: "Bursar",
    productLabel: PRODUCT_LABEL,
    items: [
      { href: "/bursar/dashboard", label: "Dashboard", icon: "home" },
      { href: "/bursar/students", label: "Students", icon: "users", activePrefix: "/bursar/students" },
      {
        href: "/bursar/fees",
        label: "Finance",
        icon: "creditCard",
        activePrefix: "/bursar/fees",
        children: [
          { href: "/bursar/fees", label: "Collections hub", icon: "creditCard", exactMatch: true },
          {
            href: "/bursar/fees/invoices",
            label: "Invoices & billing",
            icon: "receipt",
            activePrefix: "/bursar/fees/invoices",
          },
          {
            href: "/bursar/fees/payments",
            label: "Record payment",
            icon: "creditCard",
            activePrefix: "/bursar/fees/payments",
          },
          {
            href: "/bursar/fees/payments/history",
            label: "Payment history",
            icon: "receipt",
            activePrefix: "/bursar/fees/payments/history",
          },
          {
            href: "/bursar/fees/schedules",
            label: "Fee schedules",
            icon: "calendar",
            activePrefix: "/bursar/fees/schedules",
          },
          {
            href: "/bursar/fees/reports",
            label: "Reports",
            icon: "fileBarChart2",
            activePrefix: "/bursar/fees/reports",
          },
        ],
      },
    ],
  },
};
