import { Router } from "express";
import { requireAuth } from "../../middleware/auth";
import { requireRoles } from "../../middleware/rbac";
import { asyncHandler } from "../../utils/asyncHandler";
import * as c from "./academic.controller";

export const academicRouter = Router();
const academicLeads = requireRoles("admin", "headteacher");
const academicReaders = requireRoles("admin", "headteacher", "class_teacher", "subject_teacher", "bursar");
const teachingReaders = requireRoles("admin", "headteacher", "class_teacher", "subject_teacher");

academicRouter.use(requireAuth);

academicRouter.post("/years", academicLeads, asyncHandler(c.postYear));
academicRouter.get("/years", academicReaders, asyncHandler(c.getYears));
academicRouter.patch("/years/:id", academicLeads, asyncHandler(c.patchYear));
academicRouter.delete("/years/:id", academicLeads, asyncHandler(c.deleteYear));
academicRouter.post("/terms", academicLeads, asyncHandler(c.postTerm));
academicRouter.get("/terms", academicReaders, asyncHandler(c.getTerms));
academicRouter.patch("/terms/:id", academicLeads, asyncHandler(c.patchTerm));
academicRouter.delete("/terms/:id", academicLeads, asyncHandler(c.deleteTerm));
academicRouter.post("/classes", academicLeads, asyncHandler(c.postClass));
academicRouter.get("/classes", academicReaders, asyncHandler(c.getClasses));
academicRouter.patch("/classes/:id", academicLeads, asyncHandler(c.patchClass));
academicRouter.delete("/classes/:id", academicLeads, asyncHandler(c.deleteClass));
academicRouter.post("/subjects", academicLeads, asyncHandler(c.postSubject));
academicRouter.get("/subjects", teachingReaders, asyncHandler(c.getSubjects));
academicRouter.patch("/subjects/:id", academicLeads, asyncHandler(c.patchSubject));
academicRouter.delete("/subjects/:id", academicLeads, asyncHandler(c.deleteSubject));
academicRouter.post("/class-subjects", academicLeads, asyncHandler(c.postClassSubject));
academicRouter.post("/class-subjects/bulk", academicLeads, asyncHandler(c.postClassSubjectsBulk));
academicRouter.get("/class-subjects", teachingReaders, asyncHandler(c.getClassSubjects));
academicRouter.get("/class-subjects/:id", teachingReaders, asyncHandler(c.getClassSubjectById));
academicRouter.put("/class-subjects/:id", academicLeads, asyncHandler(c.putClassSubject));
academicRouter.delete("/class-subjects/:id", academicLeads, asyncHandler(c.deleteClassSubject));
academicRouter.post("/combinations", academicLeads, asyncHandler(c.postCombination));
academicRouter.get("/combinations", teachingReaders, asyncHandler(c.getCombinations));
academicRouter.get("/combinations/:id", teachingReaders, asyncHandler(c.getCombinationById));
academicRouter.put("/combinations/:id", academicLeads, asyncHandler(c.putCombination));
academicRouter.delete("/combinations/:id", academicLeads, asyncHandler(c.deleteCombination));
academicRouter.post("/combinations/:id/subjects", academicLeads, asyncHandler(c.postCombinationSubject));
academicRouter.delete("/combinations/:id/subjects/:subjectId", academicLeads, asyncHandler(c.deleteCombinationSubject));
academicRouter.post("/cbc-strands", academicLeads, asyncHandler(c.postCbcStrand));
academicRouter.get("/cbc-strands", teachingReaders, asyncHandler(c.getCbcStrands));
academicRouter.get("/cbc-strands/:id", teachingReaders, asyncHandler(c.getCbcStrandById));
academicRouter.put("/cbc-strands/:id", academicLeads, asyncHandler(c.putCbcStrand));
academicRouter.delete("/cbc-strands/:id", academicLeads, asyncHandler(c.deleteCbcStrand));
academicRouter.post("/cbc-strands/:id/sub-strands", academicLeads, asyncHandler(c.postCbcSubStrand));
academicRouter.put("/cbc-strands/sub-strands/:subStrandId", academicLeads, asyncHandler(c.putCbcSubStrand));
academicRouter.delete("/cbc-strands/sub-strands/:subStrandId", academicLeads, asyncHandler(c.deleteCbcSubStrand));
